export const tags = [
  'Auth',
  'Region',
  'User',
  'Type Operator',
  'Call Motive',
  'Area',
  'Type Requester',
  'Requester Status',
  'Requester',
  'Message',
  'Channel',
  'Call',
  'Attendance',
  'Available Time',
  'Document Type',
  'Document',
  'Report Config',
  'Dashboard',
];
