export interface FirebaseConfig {
  FIREBASE_PROJECT_ID: string;
  FIREBASE_PRIVATE_KEY: string;
  FIREBASE_CLIENT_EMAIL: string;
  FIREBASE_TYPE: string;
  FIREBASE_PRIVATE_KEY_ID: string;
  FIREBASE_CLIENT_ID: string;
  FIREBASE_AUTH_URI: string;
  FIREBASE_TOKEN_URI: string;
  FIREBASE_AUTH_PROVIDER: string;
  FIREBASE_CLIENT_CERT_URL: string;
  STAGE_DEPLOY_URL: string;
  FIREBASE_WEB_API_KEY: string;
  FIREBASE_WEB_AUTH_DOMAIN: string;
  FIREBASE_WEB_STORAGE_BUCKET: string;
  FIREBASE_WEB_MESSAGING_SENDER_ID: string;
  FIREBASE_WEB_APP_ID: string;
  FIREBASE_WEB_MEASUREMENT_ID: string;
}
